{{ if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Chart.Name }}
spec:
  parentRefs:
    {{ range .Values.gateway.parentRefs  }}
    - name: {{ .name }}
      namespace: {{ .namespace }}
    {{  end }}
  hostnames:
  - {{ .Values.host }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.path }}
    backendRefs:
    - name: {{ .Chart.Name }}
      port: {{ .Values.service.port }}
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ .Chart.Name }}
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        port: {{ .Values.service.port }}
        requestPath: {{ .Values.path }}
  targetRef:
    group: ""
    kind: Service
    name: {{ .Chart.Name }}
{{ end }}